# Generated by Django 5.0.6 on 2024-06-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("country", models.CharField(max_length=200)),
                ("lat", models.CharField(max_length=15)),
                ("lng", models.CharField(max_length=15)),
            ],
        ),
        migrations.AddConstraint(
            model_name="city",
            constraint=models.UniqueConstraint(
                fields=("name", "country"), name="unique_city_name_country_constraint"
            ),
        ),
    ]
